### DISCUSSION TITLE
Problemas de conexion entre nodos a traves de internet

### DISCUSSION THREAD

**Discussion by rubensantibanezacosta** [opencanarias/taple-client#23] [General]
Estoy teniendo problemas con la comunicacion entre un nodo expuesto en internet, y un nodo que ejecuto en local. 

He configurado la gobernanza para añadir al segundo nodo como miembro:

```json
 "members": [
            {
              "id": "tokenmys",
              "tags": {},
              "description": "Aplicacion tokenMYs",
              "key": "ETxUNXrMVNJiHNroe6F591BBchYNklPNbDOfy6wPm7v0"
            },
            {
              "id": "ayuntamiento",
              "tags": {},
              "description": "Ayuntamiento",
              "key": "E81XuTON9wzLLEM8tckEuJPocRk5IzRxVEoDtSoBS"
            }
          ],
```
He definido la variable KNOWN_NODES del segundo nodo, obtenida del los logs del primero:

- Logs
```
tokenmys_1  | [2023-04-12T16:23:30Z INFO  network::network] RED: "/ip4/64.225.68.66/tcp/40000/p2p/12D3KooWF94zhYqrh9hiuEUYqivrbf2LfTZDhW2nHmXBwoEfHNCC"
```
- Variable de entorno del segundo nodo:
```
TAPLE_NETWORK_KNOWNNODES=/ip4/64.225.68.66/tcp/40000/p2p/12D3KooWF94zhYqrh9hiuEUYqivrbf2LfTZDhW2nHmXBwoEfHNCC
```

Docker compose del primero:
```yml
version: "3.3"

services: 
  tokenmys:
    image: rubensantibanezacosta/taple-client-node-signer:latest
    build:
      context: ./node_taple_sign
      dockerfile: Dockerfile
    ports:
      - "3000"
      - "40000"
      - "30000"
    network_mode: "host"
    env_file:
      - tokenmys.env
      - ./env.api
    volumes:
      - ./data_tokenmys_data:/tmp/data
```
- Docker compose del segundo:
```yml
version: "3.3"

services: 
  ayuntamiento:
    image: rubensantibanezacosta/taple-client-node-signer:latest
    build:
      context: ./node_taple_sign
      dockerfile: Dockerfile
    ports:
      - "3001"
      - "40001"
      - "30001"
    network_mode: "host"
    env_file:
      - ayuntamiento.env
      - ./env.api
    volumes:
      - ./data_ayuntamiento:/tmp/data
```

La imagen la construi basando en la vuestra, y corriendo un servidor de express en paralelo que cubre la funcionalidad de firma, por si suena raro la imagen 'rubensantibanezacosta/taple-client-node-signer:latest'

Decir el primer nodo responde perfectamente a todas las operaciones REST de la documentación. ¿Se os ocurre que puede ser?

Gracias!!
